name: craftiservi-discord
version: '1.0'
main: com.x_tornado10.craftiservidiscord.craftiservi_discord
api-version: 1.19
authors: [ x_Tornado10 ]
description: This Plugin is an extension for the crafti-servi plugin. This extension allows discord sync
#depend:
#  - Craftiservi

