name: craftiservi-discord
version: '1.4'
main: com.x_tornado10.craftiservi_discord.craftiservi_discord
api-version: 1.20
authors: [ x_Tornado10 ]
description: This Plugin is an extension for the crafti-servi plugin. This extension allows discord sync

